### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/Calculater#1]
readme file is to be updated .
you can decorate it , add stickers , screenshots etc ...
any kind of contribution is welcome

**Comment by rivhx** [comment]
I will contribute

**Comment by srbcheema1** [comment]
thanks @rivhx 
also remember there is a secret in this app
type 1501 and click on menu button to explore more settings

**Comment by srbcheema1** [comment]
@rivhx 
do give a STAR to repository if you found it interesting

**Comment by Adroit11** [comment]
Would love to contribute

**Comment by srbcheema1** [comment]
@Adroit11 
go for it :+1:

**Comment by ghost** [comment]
Do you want to add license file link in README.md?

**Comment by srbcheema1** [comment]
@drashti4 
sure you may go for it :)

**Comment by ghost** [comment]
I have added license in readme itself as it is short. :) please check it.

**Comment by srbcheema1** [comment]
thanks every one 
@drashti4 
@rivhx 
@Adroit11 


once have a look at this 
it is more than a basic calculator . 
it was made for trick basically 
type 1501 and click on menu button and explore additional settings
click on Advance Settings and create a key value pair 
key must be 4 digits long 
value must be 8 digits long 

now the trick begins 
as you type the key and press '='
then as you begin doing calculations 
after 4 = signs pressed calculator will show the result "value you fixed in advance settings"

watch this video 
this calculator works the same 
https://www.youtube.com/watch?v=hNkF7I1K8oo
